version: "3.8"

services:
  api:
    image: backend
    ports:
      - "8080:80"
    networks:
      - lager
    
  frontend:
    image: frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - lager

  database:
    image: mysql
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yeet
      MYSQL_DATABASE: Lager
    ports:
      - 63306:3306

  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - database

networks:
  lager:
    name: lager