ALTER TABLE CategoryTable
MODIFY COLUMN CategoryId INT AUTO_INCREMENT PRIMARY KEY,
MODIFY COLUMN CategoryName VARCHAR(100) NOT NULL;

ALTER TABLE ItemTable
MODIFY COLUMN ItemStatus INT NOT NULL FOREIGN KEY REFERENCES StatusTable(StatusId),
MODIFY COLUMN ItemCategory INT NOT NULL FOREIGN KEY REFERENCES CategoryTable(CategoryId);

FOREIGN KEY (ItemStatus) REFERENCES StatusTable(StatusId),
